name: 公告

on:
  watch:
    types: started
#  schedule:
#    - cron: 30 23 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    
    - name: set-env
      run: echo "::set-env name=DATE::$(TZ=UTC-8 date "+%Y.%m.%d %H:%M:%S")"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} 🚀 公告 | 有重大更新时发布
        allowUpdates: true
        tag: 公告
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          🚀 推荐本人[➽自用机场](https://moo.pet/Rxd4O),返佣是我持续编译的最大动力.
          🚀 本站下载需要黄金梯，如需国内下载、添加额外插件或依赖、查看固件说明等，请移步[➽我的网盘](http://bin000000.top:9666).
          🚀 意见建议等可以提交Issues。也欢迎有兴趣的机油共同维护本仓库（Pull请用中文说明，本人近乎英盲 ）.
          🚀 最新公告：[➽4月13日](https://github.com/bin20088/Bin/blob/master/.github/workflows/公告.md).
