name: 公告

on:
  repository_dispatch:
#  watch:
#    types: started
#  schedule:
#    - cron: 30 23 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    
    - name: set-env
      run: echo "::set-env name=DATE::$(TZ=UTC-8 date "+%Y.%m.%d %H:%M:%S")"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} 🚀 公告 | 有重大更新时发布
        allowUpdates: true
        tag: 公告
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          🚀 推荐本人[➦自用机场](https://moo.pet/Rxd4O),返佣是我持续编译的最大动力.本仓库永久每天早上会编译出最新固件。
          🚀 本站下载需要黄金梯，如需国内下载/添加额外插件及依赖请移步[➦我的网盘](http://bin000000.top:9666)开发版目录下查找安装即可.   
          🚀 食用必看最新[➦4月16日公告及固件说明](https://github.com/bin20088/Bin/blob/master/.github/workflows/公告.md)。
